name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/secup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci #ci-analog of install , but better.
      - name: Run tests
        run: npm test
